# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Add python required modules
        run: |
          python -m pip install pyautogui
          python -m pip install pillow
          python -m pip install requests
          python -m pip install pywin32
      - name: Run tests
        run: |
          python main.py
      - name: Archive result
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.html
      - name: Deploy pages
        run: |
          git clone --single-branch --branch gh-pages git@github.com:daid/GBEmulatorShootout.git pages
          cp results.html pages/index.html
          cd pages && git commit -a -m 'Update' && git push
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
